src/Entity/Answer.php
<?php

namespace App\Entity;

use App\Repository\AnswerRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AnswerRepository::class)
 */
class Answer
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Question::class, inversedBy="answers")
     */
    private $question;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $answer;

    /**
     * @ORM\Column(type="boolean")
     */
    private $expected_answer;

    private $expected_answer_crypt;
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getQuestion(): ?Question
    {
        return $this->question;
    }

    public function setQuestion(?Question $question): self
    {
        $this->question = $question;

        return $this;
    }

    public function getAnswer(): ?string
    {
        return $this->answer;
    }

    public function setAnswer(string $answer): self
    {
        $this->answer = $answer;

        return $this;
    }


    public function setExpectedAnswer(bool $expected_answer): self
    {
        $this->expected_answer = $expected_answer;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getExpectedAnswer()
    {
        return $this->expected_answer;
    }


    /**
     * @return mixed
     */
    public function getExpectedAnswerCrypt()
    {
        return password_hash($this->expected_answer,PASSWORD_DEFAULT);
    }

    /**
     * @param mixed $expected_answer_crypt
     */
    public function setExpectedAnswerCrypt($expected_answer_crypt): void
    {
        $this->expected_answer_crypt = $expected_answer_crypt;
    }


}

src/Controller/QuizController.php
<?php

namespace App\Controller;

use App\Entity\Category;
use App\Entity\History;
use App\Entity\Quizz;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class QuizController extends AbstractController
{


    #[Route('/', name: 'quiz')]
    public function index(Request $request,PaginatorInterface $paginator): Response
    {
        if (isset($_COOKIE['history'])&&$this->getUser()==null){
            $history=json_decode($_COOKIE['history'],true);
            foreach ($history as $key=> $item){
                $history[$key]['quiz']=$this->getDoctrine()->getRepository(Quizz::class)->find($item['quizz_id']);
            }
            $history=array_reverse($history);

        }else{
            $history=$this->getDoctrine()->getRepository(History::class)->findBySortedAsc($this->getUser());
            if ($history==null){
                $history=0;
            }
        }

        $quizList = $this->getDoctrine()->getRepository(Quizz::class)->findAll();
        $categories = $this->getDoctrine()->getRepository(Category::class)->findAll();
        $quizList=$paginator->paginate($quizList,
                             $request->query->getInt('page',1),9);
        return $this->render('quiz/index.html.twig', [
            'quizs' => $quizList, 'categories' => $categories,'history'=>$history
        ]);

    }


    #[Route('/start-quiz/{slug}', name: 'start-quiz')]
    public function startQuiz($slug, Request $request,EntityManagerInterface $manager)
    {

        $recorded=null;

        if (isset($_COOKIE['history'])){
            $history=json_decode($_COOKIE['history'],true);
        }else{
            $history=[];
        }



        $i = 0;
        $quiz = $this->getDoctrine()->getRepository(Quizz::class)->findOneBy(['slug'=>$slug]);
        $id=$quiz->getId();

        $questions = $quiz->getQuestions()->toArray();


        if ($this->getUser()!==null){
            $bestScore=$this->getDoctrine()->getRepository(History::class)->findBestScore($this->getUser(),$quiz);
        }

        if (!isset($bestScore[0])){
            $bestScore=[''];
        }else{
            $bestScore=$bestScore[0];
        }

        foreach ($questions as $question) {
            $rep = $question->getAnswers()->toArray();
            shuffle($rep);
            $rep = new  ArrayCollection($rep);
            $question->setAnswers($rep);
        }


        if (sizeof($request->request->all()) > 0) {

            foreach ($request->request->all() as $req) {
                $reqs[] = $req;
            }

            foreach ($quiz->getQuestions() as $key => $question) {

                if (password_verify(true, $reqs[$key])) {
                    $i++;
                    $question->setStatus('ok');

                } else {
                    $question->setStatus('ko');
                }


            }

            $score=$i / sizeof($quiz->getQuestions()) * 100;

            if (isset($_COOKIE['history'])) {
                $data = json_decode($_COOKIE['history'], true);
            }
            if (isset($_COOKIE['last_score'])){
                $score = $score > $_COOKIE['last_score']?$score:$_COOKIE['last_score'];
            }
            $recorded=$i / sizeof($quiz->getQuestions()) * 100;

            if ($this->getUser()==null){
                $data[] = ['quizz_id' => $id, 'score' => $recorded];
                setcookie('history', json_encode($data), time() + 3600 * 8760, '/');
                setcookie('last_score', $score,time() + 3600 * 8760, '/start-quiz/'.$slug);
            }else{
                /*TODO record in db score + quizz id*/
                $record=new History();
                $record->setUser($this->getUser())
                    ->setQuiz($quiz)
                    ->setScore($recorded)
                    ->setCreatedAt(new DateTime());
                $this->getUser()->addHistory($record);
                $manager->persist($record);
                $manager->flush();

            }


        }
        return $this->render('quiz/quiz.html.twig', ['quiz' => $quiz, 'cookies' => $_COOKIE,'bestScore'=>$bestScore,'scoreRecorded'=>$recorded]);
    }
}

templates/quiz/index.html.twig
{% extends 'quiz/template.html.twig' %}

       {% block middle %}

           <ol class="list-group list-group-numbered  sticky-top">
               <li class="h3 list-group-item d-flex justify-content-between align-items-start bg-yellow-2 text-light">
                   Quizs
               </li>
               {% for quiz in quizs %}

                   <li class="list-group-item d-flex justify-content-between align-items-start custom-li">
                       <div class="w-100 d-flex justify-content-between">
                           <a href="{{ path('start-quiz',{'slug': quiz.slug}) }}"
                              class="fw-bold h5 custom-a-yellow">{{ quiz.name }}</a>
                           <a style="color: {{ quiz.category.color }}" class="anchors" href="{{ path('category',{'slug': quiz.category.slug}) }}">
                               <i  class="{{ quiz.category.icon }}" aria-hidden="true"></i>
                               {{ quiz.category.category }}</a>
                       </div>
                   </li>
               {% endfor %}
               <li class="list-group-item ">
                   <div class="d-flex justify-content-center">
                       {{ knp_pagination_render(quizs) }}
                   </div>
               </li>
           </ol>

       {% endblock %}

templates/quiz/quiz.html.twig
{% extends 'base.html.twig' %}

{% block title %} Quiz: {{ quiz.name }}{% endblock %}

{% block body %}
    <div class="container-fluid">

        <div style="background-color: {{ quiz.category.color }}"  class="jumbotron jumbotron-fluid mt-5 rounded text-center">
            <div  class="container d-flex justify-content-between" >

                {% if scoreRecorded is defined and  scoreRecorded is not null%}
                    <div>
                        <h1 style="font-size: 3em;" class="text-light custom-font">{{ quiz.name }}</h1>
                        <h4 class="text-grey-custom">Dernier score : {{ scoreRecorded }} %</h4>
                    </div>

                {% else %}
                    <div>
                        <h1 style="font-size: 3em;" class="text-bold text-light custom-font">{{ quiz.name }}</h1>
                    </div>

                {% endif %}
                {% if app.user is  null %}
                {% if cookies.last_score is defined %}
                    <span style="height: 3em;width: 3em;line-height: 3em" class="fa-stack">
                <i class="fas fa-star fa-3x   text-warning" aria-hidden="true">
                    <strong class="fa-stack-2x text-light" style="z-index: 200;font-size: 40%;position: absolute;bottom: 20%; margin: 2px"> {{ cookies.last_score | round }}</strong>
                </i>
                </span>
                {% endif %}
                {% else %}

                {% if bestScore.score is defined %}
                    <span style="height: 3em;width: 3em;line-height: 3em" class="fa-stack">
                <i class="fas fa-star fa-3x   text-warning" aria-hidden="true">
                    <strong class="fa-stack-2x text-light" style="z-index: 200;font-size: 40%;position: absolute;bottom: 20%; margin: 2px"> {{ bestScore.score }}</strong>
                </i>
                </span>
                {% endif %}


                {% endif %}

            </div>
        </div>




        <form class="text-justify" method="post" action="{{ path('start-quiz',{'slug': quiz.slug}) }}">
            <div class="container ">
                <div class="row">
        {% for question in quiz.questions %}

                <div class="col-12 text-justify p-3 rounded bg-light-custom m-2 p-1">



                {% if  question.status is not null  %}
                {% if question.status=='ok' %}
                    <h4 class="font-weight-bold text-success"><i class="fa fa-check text-success" aria-hidden="true"></i>  {{ question.question }}</h4>
                {% else %}
                    <h4 class="font-weight-bold text-danger"><i class="fa fa-times text-danger" aria-hidden="true"></i>  {{ question.question }}</h4>
                {% endif %}

                    {% else %}
                        <p class=" h4 font-weight-bold custom-text-yellow text-center">{{ question.question }}</p>
                {% endif %}
                    <div class="mt-3">



                {% for answer in question.answers %}
                    <div class="form-check ml-5 mt-2">
                        <input class="form-check-input" required type="radio" id="{{ answer.id }}" name="{{ question.id }}" value="{{ answer.expectedAnswerCrypt }}">
                        <label class="form-check-label h5 custom-text-blue-light"  for="{{ answer.id }}">{{ answer.answer }}</label>
                    </div>
                {% endfor %}
                    </div>
            </div>

        {% endfor %}
            <div class="text-center m-4">
                <button class="btn btn-lg btn-success" type="submit">Envoyer</button>
            </div>

                </div>

            </div>

        </form>


    </div>
{% endblock %}

templates/quiz/template.html.twig
{% extends 'base.html.twig' %}

{% block title %}Quiz{% endblock %}

{% block body %}


    <i class="fa fa-star-o fa-3x   text-warning" aria-hidden="true"></i>
    <div class="container-fluid text-center">

        <div class="row">
            <div class="col-5 col-lg-3 mt-4">
                <ol class="list-group list-group-numbered">
                    <li class="h3 list-group-item d-flex justify-content-between align-items-start bg-yellow-1 text-light">
                        Catégories
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-start custom-li">
                        <a href="{{ path('quiz') }}"
                           class="fw-bold h5 ms-2 me-auto w-100 custom-a-yellow">
                            Tous</a>
                        <span style="background-color: #cb7905"
                              class=" h5 p-2 badge text-light rounded-pill">{{ categories |length }}</span>
                    </li>
                    {% for category in categories %}
                        <li class="list-group-item d-flex justify-content-between align-items-start custom-li">
                            <a href="{{ path('category',{'slug': category.slug}) }}"
                               class="fw-bold h5 ms-2 me-auto w-100 custom-a-yellow">
                                {{ category.category }}</a>
                            <span style="background-color: {{ category.color }}"
                                  class=" h5 p-2 badge text-light rounded-pill">{{ category.quizzs.count }}</span>
                        </li>
                    {% endfor %}
                </ol>
            </div>
            <div class="col-7 col-lg-6 mt-4">
                {% block middle %}

                {% endblock %}
            </div>
            <div class="col-lg-3 mt-4">
                {% if app.user is  empty %}

                    {% set i=0 %}
                    {% for his in history %}
                        {% set i=i+his.score %}
                    {% endfor %}
                    {% set l= history | length %}
                    {% set rank=i/l %}
                {% else %}

                    {% set i=0 %}
                    {% for his in history %}
                        {% set i=i+his.score %}
                    {% endfor %}
                    {% set l= history | length %}
                    {% set rank=i/l %}


                {% endif %}
                <ul class="list-group  sticky-top">
                    <li class=" list-group-item d-flex justify-content-between align-items-start bg-blue-1 text-light">
                        <span class="h3"> Rang</span>
                        <span style="height: 3em;width: 3em;line-height: 3em" class="fa-stack">
                                 <i class="fas fa-star fa-3x   text-warning" aria-hidden="true">
                                     <strong class="fa-stack-2x text-light"
                                             style="z-index: 200;font-size: 40%;position: absolute;bottom: 20%; margin: 2px"> {{ rank|round }}</strong>
                                 </i>
                                </span>
                    </li>
                    <li class=" list-group-item d-flex justify-content-between align-items-start bg-blue-1 text-light">
                        <span class="font-weight-bold"> Vos dernières 10 parties </span>
                    </li>
                    {% set i=0 %}
                    {% if history is iterable %}

                        {% for item in history %}
                            {% if i<10 %}
                                <li class="list-group-item d-flex justify-content-between align-items-start custom-li">

                                    <a href="{{ path('start-quiz',{'slug': item.quiz.slug}) }}"
                                       class="h5 ms-2 me-auto w-100 custom-a-yellow">
                                        {{ item.quiz.name }}
                                    </a>

                                    <span class="p-2 badge bg-warning text-light rounded-pill">{{ item.score }}</span>
                                </li>
                            {% endif %}
                            {% set i=i+1 %}
                        {% endfor %}
                    {% endif %}
                </ul>


            </div>

        </div>
    </div>
{% endblock %}